name: gruns

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: true

      - uses: imjasonh/setup-ko@v0.6
      - name: Test
        run: go test -v ./...
      - name: Build
        run: ko build --bare --platform=linux/amd64,linux/arm64,darwin/arm64 --local
