name: gruns

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: true

      - uses: imjasonh/setup-ko@v0.6
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Push
        run: |
          ko build --bare -t latest ./
